services:
  postgres:
    image: postgres:latest
    container_name: postgres_example_api
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: example_api
      PGDATA: /var/lib/postgresql/data/pgdata_example_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata_example_api:/var/lib/postgresql/data/pgdata_example_api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    restart: always
    tty: true
    stdin_open: true

volumes:
  pgdata_example_api: